development:
  cloud_name: adewunmi97
  api_key: '782672862225549'
  api_secret: DDMaWc-XJddeDReQE3_NnZaOyQg
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: adewunmi97
  api_key: '782672862225549'
  api_secret: DDMaWc-XJddeDReQE3_NnZaOyQg
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: adewunmi97
  api_key: '782672862225549'
  api_secret: DDMaWc-XJddeDReQE3_NnZaOyQg
  enhance_image_tag: true
  static_file_support: false